카메라 여부 확인하는 if문 추가
carpenstreet/blender pull request #285
Opened 2023-01-30 09:19 UTC by HaYeonKim00

## 관련 링크
[카메라가 없을 때 Quick Render 에러 발생-태스크 카드](https://www.notion.so/acon3d/Quick-Render-2db84d5e85634219ac3c179003b7dc28)

## 발제/내용
- 카메라가 없을 때 Quick Render 에서 에러가 발생함

## 대응
- 세가지 랜더에 모두 카메라 여부 확인하는 if문 추가

### 어떤 조치를 취했나요?
- 세가지 랜더에 모두 카메라 여부 확인하는 if문 추가

2023-02-13 02:13 UTC, sdkfile requested changes
수정사항 적어드렸습니다.

2023-02-13 02:13 UTC, sdkfile commented on release/scripts/startup/abler/export_tab/export_control.py
> +        if bpy.context.scene.camera:
@HaYeonKim00 이거 여기에 if문이 들어가야 하는게 맞나요? [에러링크](https://carpenstreet.sentry.io/issues/3860744920/?project=6046815&referrer=slack)에 보면 해당 에러가 나는 부분은 수정하신 부분이 아니고 다른 부분에서 나는 것 같습니다.

물론 [태스크 카드 링크](https://www.notion.so/acon3d/Quick-Render-2db84d5e85634219ac3c179003b7dc28)에 적으신 것처럼 처리하는 것도 필요하긴 한데, 에러 자체를 방지하는 변경사항도 한번 넣어주셔야 할 것 같습니다!

2023-02-14 04:12 UTC, sdkfile requested changes

2023-02-14 04:12 UTC, sdkfile commented on release/scripts/startup/abler/lib/render.py
> +    if not scene.camer.data:
@HaYeonKim00 오타... 빌드 꼭 해보시고 커밋해주세요

2023-02-14 04:17 UTC, HaYeonKim00 commented on release/scripts/startup/abler/lib/render.py
> +    if not scene.camer.data:
마음이 급했나 봅니다. 확인 잘 하겠습니다.

2023-02-16 04:38 UTC, Youdiie requested changes

2023-02-16 04:38 UTC, Youdiie commented on release/scripts/startup/abler/export_tab/export_control.py
> +        if bpy.context.scene.camera:
draw(self, context)의 context가 bpy.context임니다.
그래서 scene = context.scene을 위로 올리고 if문 내용 중복을 줄이면 더 좋을거 같아요

2023-02-16 05:42 UTC, HaYeonKim00 commented on release/scripts/startup/abler/export_tab/export_control.py
> +        if bpy.context.scene.camera:
넵!!

2023-02-20 04:57 UTC, HaYeonKim00 commented on release/scripts/startup/abler/export_tab/export_control.py
> +        if bpy.context.scene.camera:
@Youdiie 변경했습니다!

2023-02-20 05:07 UTC, Youdiie approved these changes

2023-02-20 11:20 UTC, sdkfile approved these changes

2023-02-23 04:52 UTC, merged