bpy.context.window_manager.set_fileselect_title를 확인하는 If문 추가
carpenstreet/blender pull request #287
Opened 2023-01-30 09:35 UTC by HaYeonKim00

## 관련 링크
[file_view_title에서 set_fileselect_title이 없는 에러-테스크 카드](https://www.notion.so/acon3d/file_view_title-set_fileselect_title-98b55d3116f942f69759f0d63dd7be35)

## 발제/내용
- file_view.py에서 window_manager에 set_fileselect_title이 없어서 에러 발생

## 대응
- `file_view_title()`에서 `bpy.context.window_manager.set_fileselect_title`를 확인해줘야 함.

### 어떤 조치를 취했나요?
- `bpy.context.window_manager.set_fileselect_title`를 확인하는 if문 추가

2023-02-02 08:41 UTC, sdkfile commented
@HaYeonKim00 개발 캠페인 참고해서 PR 제목 다시 부탁드릴게용~

2023-02-02 10:59 UTC, HaYeonKim00 commented
> @HaYeonKim00 개발 캠페인 참고해서 PR 제목 다시 부탁드릴게용~

너무 제목이 방대해졌는데, 제가 이 에러의 원인에 대해 자세히 몰라서 그런것 같습니다. 에러 카드 작성자께 질문드리고 한번 다시 수정해보겠습니다.

2023-02-13 02:16 UTC, sdkfile requested changes

2023-02-13 02:16 UTC, sdkfile commented on release/scripts/startup/abler/lib/file_view.py
> +    if bpy.context.window_manager.set_fileselect_title:
이 부분이 왜 추가되었는지 노션 카드 링크와 함께 주석 달아주시면 좋을 것 같습니다.

2023-02-14 04:13 UTC, sdkfile approved these changes

2023-02-16 04:39 UTC, Youdiie requested changes

2023-02-16 04:39 UTC, Youdiie commented on release/scripts/startup/abler/lib/file_view.py
> +    if bpy.context.window_manager.set_fileselect_title:
if문과 아래 함수, lambda에서 중복되는 부분 줄일수 있을거 같네요

2023-02-16 05:46 UTC, HaYeonKim00 commented on release/scripts/startup/abler/lib/file_view.py
> +    if bpy.context.window_manager.set_fileselect_title:
함수에도 쓸 수 있다고 생각하지 못했는데, := 이 연산자 써서 줄이면 되는거겠죠?

2023-02-20 04:57 UTC, HaYeonKim00 commented on release/scripts/startup/abler/lib/file_view.py
> +    if bpy.context.window_manager.set_fileselect_title:
@Youdiie 확인부탁드립니다!

2023-02-20 05:05 UTC, Youdiie approved these changes
오.. 제가 생각한건 bpy.context.window_manager까지만이었는데 함수명도 바다코끼리가 되군요 싱기방기
어프룹임니다~

2023-02-23 04:51 UTC, merged