줌아웃을 해도 오브젝트가 보일 수 있도록 카메라 렌즈 값 조정
carpenstreet/blender pull request #288
Opened 2023-01-31 06:43 UTC by HaYeonKim00

## 관련 링크
[일정 범위 이상 줌아웃시 개체가 안보이는 에러-테스크 카드](https://www.notion.so/acon3d/3d433a89042a4fd4a6a9a38b282c09f3)

## 발제/내용
- 트위터 CS: 시야 확보 문제

## 대응
- 카메라 렌즈 값의 범위 조정

### 어떤 조치를 취했나요?
- `camera.clip_end`범위를 조정하여 초기 카메라 clip_end를 100000m로 적용

2023-01-31 07:24 UTC, Youdiie requested changes

2023-01-31 07:24 UTC, Youdiie commented on release/scripts/startup/abler/pref.py
> +    bpy.data.cameras[0].clip_end = 100000
bpy.data.cameras[0]로 하면 카메라 하나만 설정이 될거에요. for문 써서 카메라 전체에 설정하는걸로 바꿔볼까요?

2023-01-31 07:33 UTC, HaYeonKim00 commented on release/scripts/startup/abler/pref.py
> +    bpy.data.cameras[0].clip_end = 100000
넵! 수정했습니다!

2023-01-31 07:46 UTC, Youdiie commented on release/scripts/startup/abler/pref.py
> +    for i in range(len(bpy.data.cameras)):
오호.. 이거 신박한 방법이네요ㅋㅋ 그냥 for i in bpy.data.cameras: i.clip_end = 100000 해도 됨니당

2023-01-31 07:50 UTC, HaYeonKim00 commented on release/scripts/startup/abler/pref.py
> +    for i in range(len(bpy.data.cameras)):
앗 ㅋㅋㅋ 수정했습니다

2023-01-31 07:57 UTC, Youdiie approved these changes
빠른 개발 믓지네요
@sdkfile 근데 요거 이번 배포에 안들어가면 머지 안해야할까요?

2023-01-31 08:00 UTC, sdkfile commented
@Youdiie @HaYeonKim00 일단 머지는 하지 말고 있읍시다. 이번 버전에 들어가면 안될 것 같습니다

2023-02-13 02:19 UTC, sdkfile requested changes

2023-02-13 02:19 UTC, sdkfile commented on release/scripts/startup/abler/pref.py
> +    bpy.app.handlers.depsgraph_update_post.append(camera_length)
@HaYeonKim00 
여기 append말고 remove로 바뀌어야 함. 그리고 보시면 아시겠지만, register와 unregister는 역순이기때문에, camera_length remove하는거는 가장 위에 추가되어야 합니다.

2023-02-13 02:19 UTC, sdkfile commented on release/scripts/startup/abler/pref.py
> +    for i in bpy.data.cameras:
for문을 쓰는건 좋은데 i라는 변수명은 바꿔주시면 좋을 것 같아요. 
```python
for camera in bpy.data.cameras:
```
로 가면 어떨까 싶네요.

2023-02-16 05:50 UTC, HaYeonKim00 commented on release/scripts/startup/abler/pref.py
> +    for i in bpy.data.cameras:
수정했습니다!

2023-02-16 05:50 UTC, HaYeonKim00 commented on release/scripts/startup/abler/pref.py
> +    bpy.app.handlers.depsgraph_update_post.append(camera_length)
앗.. 넵!!!

2023-02-20 04:58 UTC, HaYeonKim00 commented on release/scripts/startup/abler/pref.py
> +    for i in bpy.data.cameras:
@sdkfile 확인부탁드립니다!

2023-02-20 04:58 UTC, HaYeonKim00 commented on release/scripts/startup/abler/pref.py
> +    bpy.app.handlers.depsgraph_update_post.append(camera_length)
@sdkfile 수정했습니다!

2023-02-21 01:31 UTC, sdkfile commented on release/scripts/startup/abler/pref.py
> +    bpy.app.handlers.depsgraph_update_post.append(camera_length)
이거 수정 덜되었어요. camera_length.remove가 제일 위에 있어야 하는거 수정해주세요~ @HaYeonKim00

2023-02-21 01:31 UTC, sdkfile commented on release/scripts/startup/abler/pref.py
> +    for i in bpy.data.cameras:
이건 확인입니다.

2023-02-21 01:37 UTC, HaYeonKim00 commented on release/scripts/startup/abler/pref.py
> +    bpy.app.handlers.depsgraph_update_post.append(camera_length)
이제 이해했습니다! 수정했습니다ㅏㅏ @sdkfile

2023-02-21 05:54 UTC, sdkfile approved these changes
확인했습니다~ @HaYeonKim00

2023-02-23 04:53 UTC, HaYeonKim00 commented
> @Youdiie @HaYeonKim00 일단 머지는 하지 말고 있읍시다. 이번 버전에 들어가면 안될 것 같습니다

@sdkfile 이건 혹시 이번버전==3월 유지보수 릴리즈 인가요?

2023-02-23 05:05 UTC, sdkfile commented
아 이거 이제 머지해도 됩니다! @HaYeonKim00

2023-02-23 05:05 UTC, merged