오브젝트가 없거나 선택되지 않았을 때 그룹 네비게이션을 사용하면서 발생하는 문제
carpenstreet/blender pull request #293
Opened 2023-02-07 05:47 UTC by HaYeonKim00

## 관련 링크
[Group Navigation 에서 선택된 개체가 없을 때 go_top 에러 발생 - 에러카드](https://www.notion.so/acon3d/Group-Navigation-go_top-f5f6b128c437483cabf2e228b00e8f6a)
[active_object가 없을 때 그룹네비게이션 parent 에러- 에러카드](https://www.notion.so/acon3d/active_object-parent-8382b758e6a84490a6f46d1973253f7a)

## 발제/내용
- 오브젝트가 없거나 선택되지 않았을 때 그룹 네비게이션을 사용하면서 발생하는 문제

## 대응

### 어떤 조치를 취했나요?

- obj가 none인지 확인하는 if문과 go_up과 go_top의 if문 조건을 동일하게 맞췄습니다.

2023-02-13 02:30 UTC, sdkfile requested changes

2023-02-13 02:30 UTC, sdkfile commented on release/scripts/startup/abler/scene_tab/object_control.py
>          if len(self._selection_undo_stack) > 0:
`go_down`이랑 `go_bottom`에도 사실 `if obj:`가 필요한 것 같아요. 같은 방식으로 감싸주시면 좋을 것 같습니다!

2023-02-14 04:16 UTC, sdkfile approved these changes

2023-02-16 04:43 UTC, Youdiie requested changes

2023-02-16 04:43 UTC, Youdiie commented on release/scripts/startup/abler/scene_tab/object_control.py
> +        if obj:
if문이 세 개나 있는데 한줄에 다 넣을 수 있을까요? 바다코끼리랑 같이 줄일 수 있는지 확인부탁드려용

2023-02-16 05:39 UTC, HaYeonKim00 commented on release/scripts/startup/abler/scene_tab/object_control.py
> +        if obj:
이거 관련해서는 조금 질문이 있는데

1. 이게 지금 if문으로(obj, obj.parent, obj.parent.parent)를 3번 확인하는 건데, 이 네가지 버튼 모두 사용조건이 parent의 parent까지 모두 있어야 하는건가요? 그리고,
2. 만약 그렇다면 if문이 하나여도 되는게 아닌가요(obj가 없는데 parent나 parent의 parent가 구조 상 있을 수 없지 않을까요?)?
3. 그런데도 에러가 발생해서 if문을 각각 추가하고 있는 거니깐 그렇다면 또 if문이 3개가 각각 필요할 것 같구요!!

2023-02-23 03:01 UTC, sdkfile commented on release/scripts/startup/abler/scene_tab/object_control.py
> +        if obj:
@Youdiie 이거 답변 해주셔야할듯

2023-02-23 03:01 UTC, sdkfile commented on release/scripts/startup/abler/scene_tab/object_control.py
> +        if obj:
@Youdiie 이거 답변 해주셔야할듯

2023-02-24 05:30 UTC, HaYeonKim00 commented on release/scripts/startup/abler/scene_tab/object_control.py
> +        if obj:
@Youdiie 유디님 이거 관련해서 월요일에 캘린더 날려도 될까요? 아니면 슬랙에서 논의할 수 있는 내용일까요?

2023-02-24 05:35 UTC, Youdiie commented on release/scripts/startup/abler/scene_tab/object_control.py
> +        if obj:
아 제가 생각한건 다른 의미였어요.
그냥 if문 합쳐서 `if obj and obj.parent and obj.parent.parent : `
찾아보니 바다코끼리는 and가 안되네요

2023-02-24 06:14 UTC, Youdiie commented on release/scripts/startup/abler/scene_tab/object_control.py
> +                if parent.parent is not None:
엇 근데 다시보니 이거 while이었는데 요렇게 변경해도 되나요?

2023-02-24 06:27 UTC, HaYeonKim00 commented on release/scripts/startup/abler/scene_tab/object_control.py
> +                if parent.parent is not None:
앗 이부분은 while이어야 겠네요! 제가 go_up과 go_top If문을 먼저 맞추고 시작해서 놓친거 같습니다. go_bottom처럼 if문 안에 while loop이 있으면 되겠네요. 감사합니다!

2023-02-24 07:06 UTC, Youdiie approved these changes
if문 합치는건 캐롤님 편하신대로 하시죵
어프룹임다

2023-02-24 07:16 UTC, merged