SWTASK-67 grid_on_when_selected 에서 selected_objects 가 없을 때 에러 발생
carpenstreet/blender pull request #302
Opened 2023-02-21 06:52 UTC by HaYeonKim00

## 관련 링크
[grid_on_when_selected 에서 selected_objects 가 없을 때 에러 발생 -Jira 카드](https://carpenstreet.atlassian.net/browse/SWTASK-67)

## 발제/내용
- 기존에 바꾼 코드에서 `show_grid`라는 boolean값이 if문 안에서 정의되어 에러가 발생함
<img width="795" alt="Screenshot 2023-02-21 at 3 23 37 PM" src="https://user-images.githubusercontent.com/76549884/220269192-7e4fab13-f91b-426a-9d27-24f35936b2df.png">

## 대응

### 어떤 조치를 취했나요?
- `show_grid`정의 하는 부분을 if문 밖으로 수정함

2023-02-21 06:57 UTC, sdkfile requested changes
수정사항입니당 @HaYeonKim00

2023-02-21 06:57 UTC, sdkfile commented on release/scripts/startup/abler/pref.py
> +        pass
이건 `pass`가 아니고 `return`아닌가요?

2023-02-21 07:01 UTC, HaYeonKim00 commented on release/scripts/startup/abler/pref.py
> +        pass
@sdkfile return으로 하면 다시 false로 돌아가질 않아요!

2023-02-21 07:03 UTC, HaYeonKim00 commented on release/scripts/startup/abler/pref.py
> +        pass
다른 방법으로 해야겠네요..ㅠㅠ

2023-02-21 07:13 UTC, HaYeonKim00 commented on release/scripts/startup/abler/pref.py
> +        pass
Non ipify related exception occured -- 이라는 게 터미널 창에 뜹니다.

2023-02-21 07:39 UTC, sdkfile commented
구두로 논의한 내용
[링크](https://acontainer.slack.com/archives/C02K1NPTV42/p1676965129554619?thread_ts=1676964673.523499&cid=C02K1NPTV42)
참고 @HaYeonKim00

2023-02-23 02:59 UTC, sdkfile approved these changes

2023-02-23 04:08 UTC, habijung approved these changes

2023-02-23 04:40 UTC, merged