SWTASK-219 Group Navigation 에서 go_down, go_bottom 이 처음 오브젝트 선택 시 실행되지 않는 문제
carpenstreet/blender pull request #326
Opened 2023-04-07 04:55 UTC by HaYeonKim00

## 관련 링크
[관련 지라 티켓](https://carpenstreet.atlassian.net/browse/SWTASK-219)

## 발제/내용
- 처음 오브젝트를 선택했을 때 그 오브젝트가 children이 있는경우에도 go_down이나 go_bottom이 작동하지 않음

## 대응

### 어떤 조치를 취했나요?
- 처음 오브젝트를 클릭했을 때에도 go_down과 go_bottom이 적용되게 함.
- 또한 refresh_stack()이라는 함수로 클릭한 obj와 관련이 없는 것들이 stack에 있다면 stack을 초기화 함

2023-04-07 05:26 UTC, JJong84 requested changes
@HaYeonKim00 리뷰 남겨드렸습니다!

2023-04-07 05:26 UTC, JJong84 commented on release/scripts/startup/abler/scene_tab/object_control.py
> +        if obj.parent or obj.children not in self._selection_undo_stack:
이 함수가 추가된 이유가 새로 다른 오브젝트를 선택했을 때 스택을 초기화하기 위해서 일까요?

2023-04-07 05:26 UTC, JJong84 commented on release/scripts/startup/abler/scene_tab/object_control.py
> +            print(self._selection_undo_stack)
print 지워주세요~

2023-04-07 05:26 UTC, JJong84 commented on release/scripts/startup/abler/scene_tab/object_control.py
> +        if obj.parent or obj.children not in self._selection_undo_stack:
항상 stack 을 초기화하는 것이 아니니까 함수 이름을 좀더 직관적으로 바꾸면 좋을 것 같습니다~

2023-04-07 05:26 UTC, JJong84 commented on release/scripts/startup/abler/scene_tab/object_control.py
> +        if len(self._selection_undo_stack) > 0:
list 원소 있는지 체크는 단순히 `if self._selection_undo_stack` 으로 하는 것이 더 깔끔할 것 같습니다!

2023-04-07 05:26 UTC, JJong84 commented on release/scripts/startup/abler/scene_tab/object_control.py
> +            if len(self._selection_undo_stack) == 0:
이 조건은 위와 중복되는 것으로 보입니다.

2023-04-07 05:26 UTC, JJong84 commented on release/scripts/startup/abler/scene_tab/object_control.py
> +                    if i < len(obj.children):
i 가 항상 0인 것 같습니다.

2023-04-07 05:26 UTC, JJong84 commented on release/scripts/startup/abler/scene_tab/object_control.py
> +        i = 0
i 가 항상 0 인 것 같습니다.

2023-04-07 05:26 UTC, JJong84 commented on release/scripts/startup/abler/scene_tab/object_control.py
> +                        bpy.context.view_layer.objects.active = obj.children[-1]
이 부분은 최하단으로 이동하는 것이 아니라 위 go_down 가 동작이 비슷해보입니다.

2023-04-07 05:26 UTC, JJong84 commented on release/scripts/startup/abler/scene_tab/object_control.py
> +            if len(self._selection_undo_stack) == 0:
위 조건과 중복되는 것 같습니다.

2023-04-07 05:26 UTC, JJong84 commented on release/scripts/startup/abler/scene_tab/object_control.py
> +        if len(self._selection_undo_stack) > 0:
list 원소 있는지 체크는 단순히 if self._selection_undo_stack 으로 하는 것이 더 깔끔할 것 같습니다!

2023-04-07 05:26 UTC, JJong84 commented on release/scripts/startup/abler/scene_tab/object_control.py
> +                    bpy.ops.acon3d.alert(
현재 최하단이면 bottom 오브젝트라는 경고창을 띄워주는 로직을 추가하셨는데 이 부분은 @sdkfile 과 상의해보시면 좋을 것 같습니다.
(번역/기획서도 추가되어야하는 일이니)

2023-04-07 05:32 UTC, sdkfile commented on release/scripts/startup/abler/scene_tab/object_control.py
> +                    bpy.ops.acon3d.alert(
아직 코드리뷰 전이지만 남깁니다. @HaYeonKim00 
bottom 오브젝트라는 경고창을 띄워주기보다는 UI를 비활성화 하는 로직이 덜 noisy 할 것 같습니다

2023-04-18 04:23 UTC, JJong84 requested changes

2023-04-18 04:23 UTC, JJong84 commented on release/scripts/startup/abler/scene_tab/object_control.py
> +            bpy.context.view_layer.objects.active = obj.children[-1]
이 부분은 최하단으로 이동하는 것이 아니라 위 go_down 가 동작이 비슷해보입니다.

2023-04-18 04:23 UTC, JJong84 commented on release/scripts/startup/abler/scene_tab/object_control.py
> +        i = 0
필요없는 i 삭제 필요

2023-04-18 06:25 UTC, LeoParkProDev commented on release/scripts/startup/abler/scene_tab/object_control.py
> +        ):
하나의 오브젝트 셀렉후, up => down => up => down 무한 반복시 점점 스택이 차오르게 됩니다. (중복원소 생김)
그러면 추후 up down 시 훑어야할 리스트의 사이즈가 길어지는 거라서 성능상의 영향을 줄수 있어보입니다.
중복원소에 대한 append 배제 혹은,주기적 클리어를 건의드립니다.

2023-04-18 06:27 UTC, LeoParkProDev commented on release/scripts/startup/abler/scene_tab/object_control.py
> +                while len(self._selection_visited_stack) > 0:
제가 파알못이라.. 이부분도 len(STACK) > 0조건이 while STACK: 으로 바ㅣ뀌어도 똑같이 작동하는지 문의드립니다.
같다면 통일성 관점에서 없애는게 좋아보입니다.

2023-04-18 06:30 UTC, LeoParkProDev commented on release/scripts/startup/abler/scene_tab/object_control.py
> +    def _check_and_clear_visited_stack(self, obj=None):
현재 default (None) 입력을 사용하는 경우가 없어보이고, 앞으로도 사용할 일이 없어보이는데 디폴트 옵션 제거 건의드립니다.

2023-04-18 06:34 UTC, LeoParkProDev commented on release/scripts/startup/abler/scene_tab/object_control.py
> +            child not in self._selection_visited_stack for child in obj.children
대형 프로젝트에서 stack이 꽤 차고(n), child도 꽤 많다면(n) 체크로직에서 n^2 시간복잡도를 차지하는데, 이부분은 괜찮을지 문의드립니다.

2023-04-18 06:42 UTC, sdkfile commented on release/scripts/startup/abler/scene_tab/object_control.py
> +        ):
완료했습니다.

2023-04-18 06:43 UTC, sdkfile commented on release/scripts/startup/abler/scene_tab/object_control.py
> +                while len(self._selection_visited_stack) > 0:
완료했습니다.

2023-04-18 06:43 UTC, sdkfile commented on release/scripts/startup/abler/scene_tab/object_control.py
> +    def _check_and_clear_visited_stack(self, obj=None):
완료했습니다.

2023-04-18 06:55 UTC, sdkfile commented on release/scripts/startup/abler/scene_tab/object_control.py
> +            child not in self._selection_visited_stack for child in obj.children
사실... 그래봐야 몇개 안됩니다..

2023-04-18 07:10 UTC, sdkfile commented on release/scripts/startup/abler/scene_tab/object_control.py
> +        i = 0
완료

2023-04-18 07:10 UTC, sdkfile commented on release/scripts/startup/abler/scene_tab/object_control.py
> +            bpy.context.view_layer.objects.active = obj.children[-1]
완료

2023-04-18 07:15 UTC, LeoParkProDev approved these changes

2023-04-18 07:17 UTC, JJong84 commented on release/scripts/startup/abler/scene_tab/object_control.py
> +            child not in self._selection_visited_stack for child in obj.children
@sdkfile
all() 부분 `not [x for x in child if x in self._selection_visited_stack]` 로 변경하는 것은 어떻게 생각하시나요?
교집합의 원소가 없다면 True 를 반환하는 조건입니다.

2023-04-18 07:30 UTC, JJong84 approved these changes

2023-04-18 07:30 UTC, merged