SWTASK-223 macOS 에이블러 파일 뷰에서 한글 자모 깨지는 현상 수정
carpenstreet/blender pull request #327
Opened 2023-04-12 09:06 UTC by sdkfile

## 관련 링크
[Jira 티켓 링크](https://carpenstreet.atlassian.net/browse/SWTASK-223?atlOrigin=eyJpIjoiODMwNTZkYzI2ODg3NDYxZGEyZDU4YmQ3YTBmNGYyNDUiLCJwIjoiaiJ9)

## 발제/내용

- macOS에서 에이블러 한글 자모 깨지는 현상이 있음 (파일 뷰어에서만 그럼)

## 대응

### 어떤 조치를 취했나요?

- `blf_font_draw_ex` 함수에서 string들에 대한 while 문을 도는데, 이때 자모를 합칠 수 있는 케이스를 미리 선별해서 합친 문자의 unicode로 새로운 unsigned int array를 채워줌.

## 유의사항
- 나름 큰 변경사항이다보니 모든 피드백을 다 받아들이겠습니다. 빡시게 코멘트 해주세요
- 윈도우 컴이 있으신 분들은 윈도우에서 한번 빌드하여 확인 해봐주시면 감사하겠습니다.
- 쌍자음에 대해서 macOS에서는 잘 적용된 것을 확인하였습니다. 혹시 모르니 더블체크 부탁드리겠습니다.

2023-04-13 06:19 UTC, LeoParkProDev commented on source/blender/blenfont/intern/blf_font.c
> +static void join_jamos(const uint *jamos, uint *syllables)
.c 파일인데 const 는 cpp 문법이라서 혹시 특정 c 컴파일러로 수행할시 문제가 없을지 문의드립니다.

2023-04-13 06:23 UTC, sdkfile commented on source/blender/blenfont/intern/blf_font.c
> +static void join_jamos(const uint *jamos, uint *syllables)
그렇긴 하지만, blender에서는 cpp 컴파일러로 빌드해서 문제는 없을 것 같습니다.
![image](https://user-images.githubusercontent.com/43770096/231671618-0a2910c0-8e55-4ce2-9aa4-24226cdb734f.png)

2023-04-13 06:23 UTC, LeoParkProDev commented on source/blender/blenfont/intern/blf_font.c
> +    if (type == 0) {
자모타입을 0,1,2,-1 로 잘 분리해주셔서, switch case 사용하면 가독성이 늘지 않을까 생각되는데 의견만 남겨봅니당...

2023-04-13 06:24 UTC, sdkfile commented on source/blender/blenfont/intern/blf_font.c
> +    if (type == 0) {
좋은 의견입니다!
(사실 지금 상태가 가독성이 높다고는 생각되지 않긴 해서 ㅋㅋ..)

2023-04-13 07:16 UTC, sdkfile commented on source/blender/blenfont/intern/blf_font.c
> +      i += 1;
좋습니다 ++로 수정해두겠습니다~!

2023-04-13 07:54 UTC, Youdiie commented on source/blender/blenfont/intern/blf_font.c
> +    if (type == 0) {
[변수명 짓는 사이트 추천](https://allmana.tistory.com/145)

2023-04-14 04:44 UTC, sdkfile commented on source/blender/blenfont/intern/blf_font.c
> +    if (type == 0) {
@LeoParkProDev 그런데 이거 변경사항 적용해보려고 하니, `get_jamo_type`이 너무 자주나와서 오히려 가독성이 낮은 switch-case 문이 나오지 않을까 생각이 들기도 하네요? 가독성 좋은 방안의 예시를 혹시 들어주실 수 있으실까요?

2023-04-14 04:59 UTC, LeoParkProDev commented on source/blender/blenfont/intern/blf_font.c
> +      i += 1;
네넵 리졸브는 제가하는건가요?

2023-04-14 05:02 UTC, LeoParkProDev commented on source/blender/blenfont/intern/blf_font.c
> +    if (type == 0) {
그러게요.. 상황별로 해야하는 2중구조라서 큰 차이는 없을것 같습니다.

2023-04-14 05:04 UTC, habijung commented on source/blender/blenfont/intern/blf_font.c
> +      i += 1;
@LeoParkProDev 저는 보통 제가 코드 작성자 일 때 직접 하는 편입니다.

2023-04-14 05:07 UTC, LeoParkProDev commented on source/blender/blenfont/intern/blf_font.c
> +  if (jamo >= 0x1100 && jamo <= 0x115E)
여기도 마찬가지인데, 한줄짜리 분기 로직일때 하단에 UNLIKELY 매크로에서는 중괄호로 진행되고 있는데, 여기는 중괄호 없이 진행되고 있어서요. 두개중 한가지 방식으로 통일하면 더 좋을것 같다는 의견 남겨봅니당..

2023-04-14 05:23 UTC, sdkfile commented on source/blender/blenfont/intern/blf_font.c
> +    if (type == 0) {
아니면 그 int를 뭔가 가독성 높은 Constant로 지정해보는것도 좋긴 하겠네요

2023-04-14 05:24 UTC, sdkfile commented on source/blender/blenfont/intern/blf_font.c
> +      i += 1;
아 이거 실제 반영은 안했으니 제가 나중에 resolve 하겠습니다!

2023-04-14 05:24 UTC, LeoParkProDev commented on source/blender/blenfont/intern/blf_font.c
> +      uint prev_c = syllables[j - 1];
어디 남겼는지 못찾아서 다시 남깁니다.

이건 질문인데요. 파일명이 종성?으로 시작하게끔 요상한 시나리오도 가능할까요?
만약 그 시나리오가 가능하다면 index=-1 잘못된 접근이 가능해 보입니다.

2023-04-14 05:24 UTC, sdkfile commented on source/blender/blenfont/intern/blf_font.c
> +  if (jamo >= 0x1100 && jamo <= 0x115E)
확인했습니다! UNLIKELY 매크로대로 작성하는 방향이 더 좋을 것 같네요 ㅎㅎ

2023-04-14 05:25 UTC, sdkfile commented on source/blender/blenfont/intern/blf_font.c
> +      uint prev_c = syllables[j - 1];
아하 파일명이 "종성"으로 시작하는 시나리오는 가능하지 않습니다. 유니코드 한글에서는 초성 자음과 종성 자음을 따로 구분하고 있어서 그렇습니다!

2023-04-14 05:27 UTC, LeoParkProDev commented on source/blender/blenfont/intern/blf_font.c
> +      uint prev_c = syllables[j - 1];
확인 감사합니다ㅎㅎ 리졸브 부탁드립니다.

2023-04-14 05:41 UTC, habijung reviewed
확인 부탁드립니다!

2023-04-14 05:41 UTC, habijung commented on source/blender/blenfont/intern/blf_font.c
> +  if (jamo >= 0x11A8 && jamo <= 0x11C2)
각 Hex 변수 들이 어떤 글자인지 있으면 좋을 것 같습니다.

2023-04-14 05:41 UTC, habijung commented on source/blender/blenfont/intern/blf_font.c
> +    uint32_t c = jamos[i];
`c`가 `char`를 뜻하는 것일까요?

2023-04-14 05:41 UTC, habijung commented on source/blender/blenfont/intern/blf_font.c
> +          syllables[j++] = (uint)(0xAC00 + (cho * 21 + jung) * 28 + jong);
21과 28은 어떤 계산으로 나온 결과인가요?

2023-04-14 05:41 UTC, habijung commented on source/blender/blenfont/intern/blf_font.c
> +  size_t index = 0;
사용하는 곳은 완전히 다르지만 유사한 의미라서 헷갈릴 수 있을 것 같은데, 어떤 용도의 `index`일까요?

2023-04-14 05:43 UTC, sdkfile commented on source/blender/blenfont/intern/blf_font.c
> +  if (jamo >= 0x11A8 && jamo <= 0x11C2)
가독성 처리하면서 다 #define 처리해서 뭔지 알기 쉽도록 해놓겠습니다!

일단은 모두 "단일 음소"들에 대한 유니코드 헥스값들입니다!

2023-04-14 05:43 UTC, sdkfile commented on source/blender/blenfont/intern/blf_font.c
> +    uint32_t c = jamos[i];
넵 일단은 char을 뜻합니다!

2023-04-14 05:44 UTC, sdkfile commented on source/blender/blenfont/intern/blf_font.c
> +          syllables[j++] = (uint)(0xAC00 + (cho * 21 + jung) * 28 + jong);
자음의 갯수와 모음의 갯수입니다. 이것도 주석이나 가독성 처리 해두어야겠네요

2023-04-14 05:44 UTC, sdkfile commented on source/blender/blenfont/intern/blf_font.c
> +  size_t index = 0;
unicode_array에 사용되는 index값입니다. 지역변수라서 사실 크게 상관없을 것 같긴 한데, 의미 부여해서 변수 변경해둘게요

2023-04-14 06:31 UTC, habijung commented on source/blender/blenfont/intern/blf_font.c
> +  size_t index = 0;
@sdkfile 그런 용도라면 의미 부여는 굳이 안해도 괜찮을 것 같습니다!

2023-04-14 06:48 UTC, LeoParkProDev commented on source/blender/blenfont/intern/blf_font.c
> +  while (jamos[i] != 0) {
jamos에 들어오는 것이 한 글자가 아닌 전체 어절의 자모라면 LIKELY 사용은 어떤지 문의드립니다. 
그래픽 렌더링이 아니라서 별로 의미가 없을까요?

2023-04-14 06:50 UTC, JJong84 commented on source/blender/blenfont/intern/blf_font.c
> +  if (jamo >= 0x11A8 && jamo <= 0x11C2)
상수 처리 좋아요~ 😄

2023-04-14 06:59 UTC, JJong84 requested changes
@sdkfile 다른 분들도 말씀해주셨지만 전반적인 magic number 처리해주시면 가독성에 있어서 좋아질 것 같습니다!

2023-04-14 06:59 UTC, JJong84 commented on source/blender/blenfont/intern/blf_font.c
> +  if (jamo >= 0x11A8 && jamo <= 0x11C2)
0, 1, 2 등의 변수도 enum 처리하면 좋을 것 같습니다!

2023-04-14 07:18 UTC, sdkfile commented on source/blender/blenfont/intern/blf_font.c
> +  while (jamos[i] != 0) {
일단은 loop escape 케이스를 제외하면 참인 경우가 대부분이라서 LIKELY 사용이 좋을 것 같네요!

2023-04-14 07:20 UTC, Youdiie approved these changes
다른 분들의 뜨거운 리뷰 외에 추가 코멘트는 없습니다~

2023-04-14 07:20 UTC, sdkfile commented
> 다른 분들의 뜨거운 리뷰 외에 추가 코멘트는 없습니다~

정말 뜨겁네요.. 덕분에 빌드중인 제 랩탑도 뜨겁..

2023-04-17 05:08 UTC, habijung approved these changes

2023-04-17 05:14 UTC, JJong84 approved these changes

2023-04-17 05:56 UTC, LeoParkProDev approved these changes

2023-04-17 05:58 UTC, merged