const char *SkipIdentifierKeywords[] 에서 관리하는 프로퍼티를 WindowManager로 옮기기
carpenstreet/blender pull request #337
Opened 2023-04-21 06:43 UTC by Youdiie

## 관련 링크
[링크](https://carpenstreet.atlassian.net/browse/SWTASK-249)

## 발제/내용

- 프로퍼티만 변경하고 종료시 'Save changes before closing?' 문구가 뜨는 에러를 해결하기 위해 현재는 const char *SkipIdentifierKeywords[] 에서 스킵할 프로퍼티를 지정하고 있음
- WindowManager에 만든 프로퍼티는 .blend에 저장되지 않는걸 이전 리서치에서 확인(https://github.com/carpenstreet/blender/pull/140), *SkipIdentifierKeywords[] 에서 관리하는 프로퍼티를 WindowManager로 옮기기

## 대응

### 어떤 조치를 취했나요?

- const char *SkipIdentifierKeywords[] 에서 지정한 프로퍼티(`password`, `password_shown`, `username`, `show_password`, `remember_username`, `show_guide`)를 AconWindowManagerProperty 내부에서 정의
- `prop = userInfo.ACON_prop` 혹은 `get_or_init_user_info().ACON_prop` 로 지정한 prop을 모두 `prop = context.window_manager.ACON_prop`로 변경
- 관련해서 `get_or_init_user_info()` 함수는 안쓰게 됨(삭제할지는 논의후 결정)

2023-04-24 01:58 UTC, sdkfile requested changes
리뷰 완료입니다 @Youdiie

2023-04-24 01:58 UTC, sdkfile commented on release/scripts/startup/abler/general_tab/general.py
> -        userInfo = get_or_init_user_info()
`get_or_init_user_info()`가 사용되지 않고, 사실 저 이름으로써의 효용도 더이상 없을 것 같은데 삭제하는게 어떨까요?

2023-04-24 01:58 UTC, sdkfile commented on release/scripts/startup/bl_operators/wm.py
> +        prop = context.window_manager.ACON_prop
혹시의 혹시가 있을수 있으니, `context.window_manager.ACON_prop`이 존재하는지 여부에 대한 if문을 전반적으로 추가하는게 어떨까요?

2023-04-24 04:29 UTC, Youdiie commented on release/scripts/startup/bl_operators/wm.py
> +        prop = context.window_manager.ACON_prop
수정완료했습니다~ @sdkfile

2023-04-24 08:20 UTC, habijung reviewed
그러면 최종 결과가 특정 프로퍼티를 수정했을 때,
- **Save changes before closing?** 문구는 안뜨면서
- `.blend` 파일에도 저장되지는 않아야 하는 것이 맞을까요?

2023-04-25 04:30 UTC, Youdiie commented
@habijung 넵 맞습니당 
사실 지금도 저 문구는 안뜨고 있는데 해당 프로퍼티들은 const char *SkipIdentifierKeywords[]에서 관리하고 있던걸 WindowManager로 옮긴거에용

2023-04-25 04:34 UTC, habijung approved these changes
@Youdiie 아하! 그렇군요. 테스트 하다가 실행 자체는 큰 차이가 없어서 궁금했었습니다. 확인했습니다!

2023-04-25 05:34 UTC, JJong84 approved these changes
코드가 더 깔끔해진 것 같네요~ 어프룹드립니다!

2023-04-25 06:29 UTC, sdkfile commented
@Youdiie 이거 큰 문제 없는 것 같은데 @LeoParkProDev 의견 없으시면 머지 가시죠 (rebase and merge ㄱㄱ)

2023-04-25 07:05 UTC, LeoParkProDev commented on release/scripts/startup/bl_operators/wm.py
>          row.alignment = "RIGHT"
만약 prop이 없다면, 아래 alignment 및 label 설정이 작동안할텐데 이건 괜찮은건가요?
만약에 필요한 동작이라면 if 체크 이전으로 옮기는게 어떤지 의견남깁니다.

2023-04-25 07:27 UTC, Youdiie commented on release/scripts/startup/bl_operators/wm.py
>          row.alignment = "RIGHT"
prop이 없다면 에러 상황이므로 동작하지 않는게 맞는거 같습니다~

2023-04-25 07:35 UTC, merged