SWTASK-266 윈도우 런쳐 파싱 및 링크 수정 (WIP)
carpenstreet/blender pull request #339
Opened 2023-04-25 05:09 UTC by sdkfile

## 관련 링크
[지라 티켓 링크](https://carpenstreet.atlassian.net/browse/SWTASK-266?atlOrigin=eyJpIjoiOTRmOTU2MWNmMjVjNDQ4NDhlZWNkODMxZDYyY2RjODUiLCJwIjoiaiJ9)

## 발제/내용
- 다운로드 인프라가 바뀌게 됨
- XML 파일을 올려서 인프라를 사용하게 됨

## 대응

### 어떤 조치를 취했나요?
- URL이 바뀜
- macOS / Linux 등에 대한 코드를 전부 삭제함 (이제 에이블러 런쳐는 Windows 전용임)
- 각종 비합리적인 코드를 수정함
- XML을 파싱하여 현재 최신 버전을 받아올 수 있도록 로직을 수정함.

2023-05-08 08:33 UTC, Youdiie requested changes

2023-05-08 08:33 UTC, Youdiie commented on launcher_abler/AblerLauncherUtils.py
> +from __future__ import annotations
annotations는 어디에 쓰이나요?

2023-05-08 08:33 UTC, Youdiie commented on launcher_abler/AblerLauncherUtils.py
>      if sys.platform == "win32":
요거 어차피 윈도우에서만 쓰이니 `if sys.platform == "win32":` 코드는 필요없을거 같습니당

2023-05-08 08:33 UTC, Youdiie commented on launcher_abler/UpdateAbler.py
> +        if installedversion is None or not installedversion:
이거 installedversion 이 빈 스트링으로 나올수 있어서 installedversion == ""로 해야할거 같아용.
not installedversion 는 installedversion is None랑 같은 의미같습니다

2023-05-08 08:33 UTC, Youdiie commented on launcher_abler/UpdateLauncher.py
> +    if state_ui != StateUI.none:
요거 의미가 다르지 않나요?

2023-05-08 08:33 UTC, Youdiie commented on launcher_abler/UpdateLauncher.py
> +        if launcher_installed is None or not launcher_installed:
요것도 원래대로 돌려야할거 같습니다

2023-05-08 08:33 UTC, Youdiie commented on launcher_abler/UpdateLauncher.py
> +        req: str = requests.get(url).text
json에서 text로 바꾼건 xml은 text만 가능해서 인가요? 그게 아니라면 굳이 json에서 text로 바꿀 필요는 없을거 같습니다!

2023-05-09 05:44 UTC, sdkfile commented on launcher_abler/UpdateLauncher.py
> +        req: str = requests.get(url).text
넹 json이랑 xml은 구조 자체가 달라서 저렇게 했습니다~

2023-05-09 05:45 UTC, sdkfile commented on launcher_abler/AblerLauncherUtils.py
> +from __future__ import annotations
아 이거 typing에서 쓰이는건데, 혹시 python 버전 업뎃되면 typing 깨지는거 방지용 코드에요

2023-05-09 05:52 UTC, sdkfile commented on launcher_abler/UpdateAbler.py
> +        if installedversion is None or not installedversion:
호오 그러네요 이거는 수정해두겠음

2023-05-09 05:52 UTC, sdkfile commented on launcher_abler/AblerLauncherUtils.py
>      if sys.platform == "win32":
인정인정

2023-05-09 05:52 UTC, sdkfile commented on launcher_abler/UpdateLauncher.py
> +        if launcher_installed is None or not launcher_installed:
넵 이것도 원래대로 돌리겠슴당

2023-05-09 05:53 UTC, sdkfile commented on launcher_abler/UpdateLauncher.py
> +    if state_ui != StateUI.none:
이거 원래 구조가 좀 이상했어서 StateUI 구조를 살짝 바꿨어요. 테스트 해보니 이 코드로 가는게 낫더라구요

2023-05-09 07:27 UTC, sdkfile commented
@Youdiie 리뷰 요청사항 반영 완료!

2023-05-09 07:49 UTC, Youdiie approved these changes
어프룹임니다~

2023-05-09 07:51 UTC, habijung commented
@sdkfile @Youdiie 
링크 수정 관련으로 추가 및 수정된 내용 push 했습니다. 혹시 변경해야할 부분 있다면 말씀해주세요!

2023-05-09 07:56 UTC, sdkfile commented
@habijung 저 이거 확인 완료!

2023-05-09 07:59 UTC, habijung approved these changes

2023-05-09 08:09 UTC, merged