Feature/swtask 86 additional lights
carpenstreet/blender pull request #345
Opened 2023-05-02 05:59 UTC by LeoParkProDev

기존버전에서 태양광만 제공, 발광체가 아닌 다른 조명은 없었던 상황
Point, Area, Spot 타입의 조명에 대한 추가제거 기능 구현

## 관련 링크
[링크](URL)

## 발제/내용

## 대응

### 어떤 조치를 취했나요?

-

2023-05-15 07:14 UTC, JJong84 requested changes
리뷰 사항 남겨드렸습니다~

2023-05-15 07:18 UTC, LeoParkProDev commented on release/scripts/startup/abler/custom_properties.py
> +    hide: bpy.props.BoolProperty(
감사합니다 is_hidden 으로 가겠습니다!

2023-05-15 07:22 UTC, LeoParkProDev commented on release/scripts/startup/abler/style_tab/styles_control.py
> +    light_type = 'AREA'
감사합니다~

2023-05-15 07:25 UTC, LeoParkProDev commented on release/scripts/startup/abler/style_tab/styles_control.py
> +        name = "ACON_" + "_light"
감사합니다. 중간에 씬 네임 넣었다가 삭제하였는데 딱 발견해주셨네요

2023-05-15 07:33 UTC, LeoParkProDev commented on release/scripts/startup/abler/style_tab/styles_control.py
> +            name = prefix + "." + postfix
light block data 생성해야 하는 상황인데, 이름이 Unique여야 하는 상황입니다. (데이터 블록 생성함수 조건)
그래서 씬에서 유니크네임을 생성하는 로직을 가져왔습니다. 다른 좋은 의견 있으시면 남겨주시면 감사하겠습니다~~~

2023-05-15 08:13 UTC, Youdiie requested changes
<img width="569" alt="스크린샷 2023-05-15 오후 5 09 40" src="https://github.com/carpenstreet/blender/assets/87409148/f3465c1d-788b-4e07-95d8-fa2b16040d61">
light가 hide가 안되는 에러도 있습니다🥲

2023-05-15 09:14 UTC, LeoParkProDev commented on release/scripts/startup/abler/custom_properties.py
> +        data.energy = aconlight.power
이 부분 저도 고민인데  블렌더와 스냅툰에서 power라는 표현 사용하고있어서 따라갔습니다. 다른분들도 의견 남겨주세요~~~

2023-05-15 09:16 UTC, LeoParkProDev commented on release/scripts/startup/abler/style_tab/styles_control.py
> +class AddPointLightOperator(AddLightOperatorBase):
아아 이부분은 상속으로 AddLightOperaterBase 를 이용해서 상속해서 사용하고 있습니다.
3가지 조명에 따라서 다른 인풋을 넘겨줘야 해서 서로다른 light_type을 갖고 있습니다.
execute 및 기타 내부함수 로직은 같습니다.

2023-05-15 09:24 UTC, LeoParkProDev commented on release/scripts/startup/abler/export_tab/render_control.py
> +        return res
네 반영하겠습니다.

2023-05-15 09:25 UTC, LeoParkProDev commented on release/scripts/startup/abler/style_tab/styles_control.py
> +            self, context, layout, data, item, icon, active_data, active_propname
헐 black api 설치해놓고 잘못 사용하고있었네요. 싹다 한번 다시 돌려보겠습니다. 감사합니다.

2023-05-15 09:25 UTC, LeoParkProDev commented on release/scripts/startup/abler/style_tab/styles_control.py
> +    def draw_item(self, context, layout, data, item, icon, active_data, active_propname):
헐 black api 설치해놓고 잘못 사용하고있었네요. 싹다 한번 다시 돌려보겠습니다. 감사합니다.

2023-05-16 09:06 UTC, LeoParkProDev commented on release/scripts/startup/abler/export_tab/render_control.py
> +        bpy.data.screens["ACON3D"].areas[0].spaces[0].overlay.show_extras=False
오!! 그렇겠네요. 이부분 고민좀 더 해봐야겠어요.

2023-05-16 09:07 UTC, LeoParkProDev commented on release/scripts/startup/abler/style_tab/styles_control.py
> +        if not index in range(0, len(lights)):
> 방향 말씀하시는거죠? 그게 더 직관적인것 같아서 그렇게 하겠습니다!

2023-05-16 09:11 UTC, LeoParkProDev commented on release/scripts/startup/abler/custom_properties.py
> +@persistent
persistant annoation(?)을 달아야 파일 새로 불러와도, 날아가지 않는다고 해서 이렇게 적용하였습니다.
혹시나 오개념이라면 의견 남겨주세요~~~

2023-05-17 01:16 UTC, Youdiie commented on release/scripts/startup/abler/custom_properties.py
> +        data.energy = aconlight.power
저는 코드상에서 맞춰주는게 더 좋을거 같습니다~

2023-05-17 01:49 UTC, sdkfile commented
@LeoParkProDev PR 이름을 바꿔주십쇼..! `SWTASK-86 [한국어로 기능 짧게 설명]`

2023-05-17 02:02 UTC, sdkfile requested changes
무수한 변경 요청입니다.. @LeoParkProDev

2023-05-17 02:02 UTC, sdkfile commented on release/scripts/startup/abler/style_tab/styles_control.py
> +    def __generate_light_name(self) -> str:
오잉 근데 안에서만 쓰이는 함수는 언더스코어 하나 붙이는게 국룰 아니었나요?

아래는 관련 링크

[What’s the Meaning of Single and Double Underscores In Python? | by Ahmed Besbes | Towards Data Science](https://towardsdatascience.com/whats-the-meaning-of-single-and-double-underscores-in-python-3d27d57d6bd1)

2023-05-18 09:07 UTC, LeoParkProDev commented on release/scripts/startup/abler/style_tab/styles_control.py
> +    def __generate_light_name(self) -> str:
음 파이썬에서 private (은 아니지만 인척) 메소드를 명명할때 언더바 두개로 시작한다고 나와있는것 같아서 이렇게 했습니다. 
한번 확인부탁드려요!

2023-05-18 09:08 UTC, sdkfile commented on release/scripts/startup/abler/style_tab/styles_control.py
> +    def __generate_light_name(self) -> str:
언더바 하나입니다!

2023-05-19 01:42 UTC, LeoParkProDev commented on release/scripts/startup/abler/lib/scenes.py
> +def change_ui_to_show_selected_light(self, context: Context) -> None:
감사합니다~ 이부분 안그래도 찜찜했었는데 좋네요.

2023-05-19 05:24 UTC, Youdiie approved these changes
어프룹임니다~ 큰 태스크인데 고생하셨슴니당

2023-05-19 05:36 UTC, sdkfile approved these changes
고생하셨습니다!

요 태스크 마무리 해주시면서 SW사업팀에 전달하고 유저들한테 배포될 수 있는 해당 기능 매뉴얼 하나만 간단하게 작성하고 티켓도 마무리해주시면 좋을 것 같습니다! @LeoParkProDev

2023-05-19 07:31 UTC, habijung reviewed
늦은 리뷰 죄송합니다.
확인 한번 부탁드리고, 불필요한 부분이라고 생각되시면 바로 넘어가셔도 좋습니다.

2023-05-19 07:31 UTC, habijung commented on release/scripts/startup/abler/custom_properties.py
> +    cnt = len(scene.collection.objects)
`cnt`는 counter를 의미하는게 맞을까요?
아래 line 292에도 `counter`가 정의되어 있어서 어떤 의미의 counter 인지 변수명이나 주석에 포함되어 있으면 좋을 것 같습니다.

2023-05-19 07:31 UTC, habijung commented on release/scripts/startup/abler/lib/scenes.py
> +    bpy.ops.object.select_all(action='DESELECT')
Black 적용하면 `'` 이 `"` 로 변환되지 않나요? 아직 변경된 코드 전체적으로 Black 적용이 덜 된 것 같습니다.

2023-05-19 07:31 UTC, habijung commented on release/scripts/startup/abler/lib/scenes.py
> +    light.power = data.energy
`power`와 `energy`에서 `energy`로 사용한다고 이해했는데, 여기도 혹시 적용되는 부분일까요?

2023-05-19 07:31 UTC, habijung commented on release/scripts/startup/abler/custom_properties.py
> +        name="",
@LeoParkProDev (참조. @Youdiie , @sdkfile )
UI에서는 **Power**로 표기되는데, 따로 UI의 문자열을 설정하는 부분이 안보이네요.
UI의 내용을 변경할 수 있으면 이전 피드백에서 논의한 것과 같이 `name`에 **Energy**가 들어가면 좋을 것 같습니다.
블렌더의 기본 이름이 **Power**라면 변수도 `power`를 사용하는건 어떤가요?

2023-05-19 08:49 UTC, JJong84 approved these changes

2023-05-19 08:50 UTC, merged