복사된 오브젝트를 붙여넣을 때 생성되는 쉐이더에도 Shadow / Shading 옵션 값 적용하기
carpenstreet/blender pull request #354
Opened 2023-05-11 13:27 UTC by habijung

에이블러 파일 간에 복사, 붙여넣기를 하면 Shadow & Shading 옵션이 붙여넣기한 파일에서 적용되지 않음.

### 재현 방법

- ~첨부된 파일 chair.blend 를 실행함 (아무 파일이나 상관 없음)~
  - 같은 파일 내에서도 해당 오류 발생함
- 오브젝트 선택 후 복사
- 새 에이블러 실행하고 오브젝트 붙여넣기
- Style > Shadow / Shading 옵션을 껐다 켰다하면 발생함
- 임시 방편으로 에이블러 재실행하고 파일 열면 옵션 적용됨

## 작업 내용

### 원인

- 오브젝트를 복사하면 구성하는 모든 요소가 복제됨. (재질, 텍스처 이미지, 쉐이더 등)
- 이 때, 블렌더에서는 이미 같은 이름의 데이터가 존재하면 이름을 .001 방식으로 넘버링을함.
- 그래서 `ACON_nodeGroup_combinedToon` 노드 그룹이 복제되면서 `.001` 등의 숫자가 붙게되고, 토글은 원본 쉐이더 노드의 값만 바꾸기 때문에 영향이 없음.
- 구성 요소가 복제되는 부분이 문제점인지? 그렇지 않은지? 에 대해서 간단한 고민 스레드
  - [Slack](https://acontainer.slack.com/archives/C02K1NPTV42/p1683801955209529)

### 해결 방안

- 모든 요소가 하나씩 더 생기는 기존의 복제 방식을 유지하면서 노드의 값을 바꾸는 것이 좋을 것 같음.
- 툰 스타일 노드 그룹 내부에 `ACON_node_shadeMixFactor` 라는 값 노드가 있는데, `Shadow / Shading` 토글 온오프는 이 값을 변경함.
- 이 노드에는 아래와 같이 접근할 수 있음.
  ```
  bpy.data.node_groups["ACON_nodeGroup_combinedToon"].nodes["ACON_node_shadeMixFactor"].outputs["Value"].default_value = 1
  ```
- 그럼 토글 온오프를 할 때, 모든 툰 스타일 노드의 `ACON_node_shadeMixFactor` 의 값을 업데이트 하면 될 것 같음.

### 결과

![image](https://github.com/carpenstreet/blender/assets/52474700/375bd144-43af-4cbd-b017-3cf9f9c5a70e)

2023-05-12 04:23 UTC, Youdiie reviewed
몇가지 제안 드려용

2023-05-12 04:23 UTC, Youdiie commented on release/scripts/startup/abler/lib/shadow.py
> +            continue
요거 continue가 아니라 return 아닐까요?
그리고 node_groups가 있는지 검사하는거라면 for문 위에 `if not bpy.data.node_groups`가 더 좋을거 같아용

2023-05-12 04:23 UTC, Youdiie commented on release/scripts/startup/abler/lib/shadow.py
> +        if "ACON_nodeGroup_combinedToon" in node_group.name:
복사된 .001까지 가져오는 거라면 startswith()도 좋을거 같아요~
+복사된 노드그룹까지 고려하기 위한 구문임을 주석으로 남겨주세용

2023-05-12 04:23 UTC, Youdiie commented on release/scripts/startup/abler/lib/shadow.py
> +            if node:
바다코끼리는 어떨까 싶은데 바다코끼리는 type 명시가 안되군요.. (https://stackoverflow.com/questions/67828042/how-to-type-hint-with-walrus-operator)
요건 이대로 있는게 좋을거 같습니당

2023-05-12 04:34 UTC, habijung commented on release/scripts/startup/abler/lib/shadow.py
> +            continue
`bpy.data.node_groups` 사이에 정상적이지 않은 데이터가 있으면 반복문이 종료가 되면 안된다고 생각해서 `continue`를 써뒀는데, 말씀하신 내용 중 node_groups 검사를 먼저하면 문제가 없겠네요!
수정 해두겠습니다.

2023-05-12 04:40 UTC, habijung commented on release/scripts/startup/abler/lib/shadow.py
> +        if "ACON_nodeGroup_combinedToon" in node_group.name:
좋은 것 같아요~ 수정 및 설명 추가 해두겠습니다.

2023-05-12 04:40 UTC, habijung commented on release/scripts/startup/abler/lib/shadow.py
> +            if node:
음.. 그런데 여기서 굳이 Node 타입을 정의하지 않아도 될 것 같아서 오히려 유디님 제안이 더 보기 좋을 것 같습니다.

2023-05-12 05:02 UTC, habijung commented
@Youdiie 피드백 반영했습니다.

2023-05-12 05:05 UTC, Youdiie approved these changes
어프룹임니다~

2023-05-12 06:10 UTC, sdkfile requested changes
수정 한건, 질문 한건 있습니다! @habijung

2023-05-12 06:10 UTC, sdkfile commented on release/scripts/startup/abler/lib/shadow.py
> +from bpy.types import Object, Light, Context, Node
코드에서 Node 타입을 명시적으로 쓰고 있지 않은 것 같은데, 확인 부탁드립니다!

2023-05-12 06:10 UTC, sdkfile commented on release/scripts/startup/abler/lib/shadow.py
> +    if bpy.data.node_groups:
이거 말고도 다른 다양한 건들이 존재하긴 할 것 같은데, 이 태스크에서 확인할 것은 아니지만 확인을 해보셨는지 궁금합니다!

2023-05-12 07:27 UTC, habijung commented on release/scripts/startup/abler/lib/shadow.py
> +from bpy.types import Object, Light, Context, Node
해당 부분 빠져도 될 것 같습니다. 확인 감사합니다.

2023-05-12 07:30 UTC, habijung commented on release/scripts/startup/abler/lib/shadow.py
> +    if bpy.data.node_groups:
@sdkfile (참조. @Youdiie )
말씀해주셔서 확인해봤는데, 값을 변경할 수 있는 모든 옵션들이 전부 문제네요. 중요한 부분 놓칠뻔 했는데 짚어주셔서 감사합니다.
툰 스타일 노드에 속한 옵션들이 전부 적용이 되지 않는다고 보시면 될 것 같습니다. 차라리 다른 방법으로 해결하는게 필요해 보이네요.

2023-05-12 07:37 UTC, sdkfile commented on release/scripts/startup/abler/lib/shadow.py
> +    if bpy.data.node_groups:
@habijung 일단 드는 생각은, 복사된 오브젝트가 acon toonstyle 노드를 가지고 있다면, 새로 만드는 것이 아니라 원래 있던 거를 그대로 쓰는 방식으로 "복사" 로직을 바꾸는 방향으로 개발방향을 수정하는 것이 더 좋아보입니다.

티켓 업데이트하고 지금 당장 보지말고 다음에 보는게 어떨까요? 당장 해결해서 나가는건 아니니깐요

2023-05-12 07:44 UTC, habijung commented on release/scripts/startup/abler/lib/shadow.py
> +    if bpy.data.node_groups:
@sdkfile 
네, 동의합니다.
툰 스타일 쉐이더까지 전부 복사되어서 같은 표현을 내는데 전부 다른 쉐이더를 사용하는 것은 이상할 것 같습니다.
Draft로 돌리고, 추가 사항 반영해두겠습니다.

2023-05-12 08:14 UTC, habijung commented
오브젝트를 복사/붙여넣기 하면 Style 탭에 있는 `ACON_nodeGroup_combinedToon` 에 속한 모든 속성이 영향을 받으므로 태스크 범위를 수정하고 이후에 처리하기로함.

2023-05-23 08:25 UTC, Youdiie commented on release/scripts/presets/keyconfig/keymap_data/abler_default.py
> +        ("object.duplicate_move", {"type": 'V', "value": 'PRESS', "ctrl": True}, None),
태스크 카드 연결 주석만 부탁드립니다~

2023-05-23 08:31 UTC, habijung commented on release/scripts/presets/keyconfig/keymap_data/abler_default.py
> +        ("object.duplicate_move", {"type": 'V', "value": 'PRESS', "ctrl": True}, None),
업데이트 했습니다~

2023-05-23 10:08 UTC, sdkfile reviewed
질문 하나 남겨드립니다.

2023-05-23 10:08 UTC, sdkfile commented on release/scripts/presets/keyconfig/keymap_data/abler_default.py
> +        ("object.duplicate_move", {"type": 'V', "value": 'PRESS', "ctrl": True}, None),
Duplicate Objects에 대한 질문 드립니다. @habijung 
1. 한 프로세스 내에서의 Data block을 사용하는 것에 대해서는 어느정도 이해가 됩니다.
2. 다만 A.blend가 열려있고, B.blend가 열려있는 상황에서 B.blend의 한 오브젝트를 Duplicate한 뒤에, A.blend에 붙여 넣게 되면 어떤 현상이 일어나나요?

2023-05-23 11:09 UTC, sdkfile commented on release/scripts/presets/keyconfig/keymap_data/abler_default.py
> +        ("object.duplicate_move", {"type": 'V', "value": 'PRESS', "ctrl": True}, None),
일단 맥에서 빌드해서 잘 되는 것 확인했고, 맥에서는 단일 프로세스밖에 안띄워져서 해당 현상 확인 불가능했습니다..만, 

터미널로 여니깐 두개 열려서 제가 질문한 부분이 의도한 바와 똑같이 잘 작동되는 것 확인했습니다! @habijung

2023-05-24 02:05 UTC, habijung commented on release/scripts/presets/keyconfig/keymap_data/abler_default.py
> +        ("object.duplicate_move", {"type": 'V', "value": 'PRESS', "ctrl": True}, None),
@sdkfile 중요한 부분 확인 감사드립니다.
그런데 맥에서 실행이 잘되나요? 윈도우에서 창 두개 켜고 넘겨서 붙여넣기 하려고하니 안되는거 확인해서 해당 작업 revert 고려하고 있습니다.

2023-05-24 02:22 UTC, sdkfile commented on release/scripts/presets/keyconfig/keymap_data/abler_default.py
> +        ("object.duplicate_move", {"type": 'V', "value": 'PRESS', "ctrl": True}, None),
잉 맥에서는 잘 되는것 같았는데, 제가 재현을 이상하게 했을수도 있어요

2023-05-24 05:07 UTC, closed without merging

2023-05-24 05:08 UTC, habijung commented
Branch 이름을 `feature/SWTASK-326-apply-shadow-shading-after-paste`에서 `feature/SWTASK-326-paste-with-toon-style`로 변경하여 해당 PR을 닫고, 작업 완료 후 새로 오픈하겠습니다.