에이블러 스플래쉬 UX 개선 작업
carpenstreet/blender pull request #359
Opened 2023-06-08 05:58 UTC by LeoParkProDev

## 발제/내용
스플래쉬 창의  회원가입, 사용법 안내, 공지사항 등의 UX를 강화하기 위한 작업

### 어떤 조치를 취했나요?
1. 언어를 변경해도 적용안되던 공지사항, 해쉬맵(언어->내용) 으로 관리하도록 수정해서 개선
2. 회원가입 버튼의 위치 로그인창 아래로 옮겨서 UX 개선
3. 중요도에 맞게 공지사항 리스트 위치 수정

### 수정내용은 아래의 사진 참고
before
<img width="539" alt="스크린샷 2023-06-08 오후 2 55 14" src="https://github.com/carpenstreet/blender/assets/130434011/9c653367-b696-40c1-a101-6512399f598b">
after
<img width="536" alt="스크린샷 2023-06-08 오후 2 54 34" src="https://github.com/carpenstreet/blender/assets/130434011/99cf7736-235a-4c52-9f88-171277452879">

2023-06-08 11:41 UTC, sdkfile requested changes
수정사항 제안드립니다. @LeoParkProDev

2023-06-08 11:41 UTC, sdkfile commented on release/scripts/startup/bl_operators/wm.py
> +lang_notice_map = {}
파이썬에서는 map 대신에 dictionary라는 네이밍을 쓰기 때문에 `lang_notice_dict`가 어떨까요?

2023-06-08 11:41 UTC, sdkfile commented on release/scripts/startup/bl_operators/wm.py
> +def fetch_notices(lang: str):
혹시혹시나 lang이 이상한 값이나 기본값이 들어가는 것을 방지해서 기본값과 허용 string을 집어넣는게 어떨까요?

2023-06-08 11:41 UTC, sdkfile commented on release/scripts/startup/bl_operators/wm.py
> +        anchor.description_text = "Link to ABLER Instruction"
이거 번역도 들어갔나요?

2023-06-08 11:42 UTC, sdkfile commented on release/scripts/startup/bl_operators/wm.py
> +        anchor.description_text = "Link to ABLER Instruction"
이건 blender-translation PR에서 확인했습니다.

2023-06-09 05:29 UTC, habijung reviewed
확인 부탁드리고, 불필요한 부분은 Resolve 해주셔도 됩니다.

2023-06-09 05:29 UTC, habijung commented on release/scripts/startup/bl_operators/wm.py
> +                but = layout.operator("acon3d.notice", text=item["title"], icon='URL')
혹시 `but`의 의미가 버튼의 의미가 맞을까요?

2023-06-09 05:29 UTC, habijung commented on release/scripts/startup/bl_operators/wm.py
> +        # blender 관련
@sdkfile 
Blender 관련 항목을 뺄 수는 없나요? 라이센스 때문에 꼭 필요한 부분이 아니라면 공지사항 부분에는 없어도 될 것 같습니다.

2023-06-09 05:29 UTC, habijung commented on release/scripts/startup/bl_operators/wm.py
> +            anchor.href = 'https://acon3d.notion.site/Operating-ABLER-9ee94a8169a6400ab9c677dd312e5fdd?pvs=4'
`anchor` 구조가 유사하게 4번 사용되는 것 같은데, description과 언어별 링크를 받을 수 있는 함수로 나누는 것은 어떤가요? 단순한 리팩토링 작업인 것 같아 불필요하면 넘어가도 괜찮을 것 같습니다.

2023-06-09 09:49 UTC, LeoParkProDev commented on release/scripts/startup/bl_operators/wm.py
> +lang_notice_map = {}
오 그렇군요 감사합니다.

2023-06-09 09:55 UTC, LeoParkProDev commented on release/scripts/startup/bl_operators/wm.py
> +def fetch_notices(lang: str):
오 넵 그럼 안전성을 위해서 
default = None 으로 하고, 함수 내에서도 허용하는 locale값이 맞는지 체크하는 로직을 추가하겠습니다.

2023-06-09 09:56 UTC, LeoParkProDev commented on release/scripts/startup/bl_operators/wm.py
> +                but = layout.operator("acon3d.notice", text=item["title"], icon='URL')
감사합니다. 이쪽은 레거시 코드이긴한데
제 생각에도 btn이 더 좋아보여서 수정하겠습니다!

2023-06-12 10:08 UTC, sdkfile commented on release/scripts/startup/bl_operators/wm.py
> +        # blender 관련
Blender의 정책이라기보다는, 사실 블렌더 프로그램 소스코드로부터 도움을 받아서 쉽게 프로덕트를 냈기 때문에 놓지 않는 마지막 호의(?)라고 봐주시면 좋을 것 같습니다!

2023-06-12 10:10 UTC, sdkfile commented on release/scripts/startup/bl_operators/wm.py
> +            anchor.href = 'https://acon3d.notion.site/Operating-ABLER-9ee94a8169a6400ab9c677dd312e5fdd?pvs=4'
따로 함수로 빼는게 좋을 것 같습니다! @LeoParkProDev

2023-06-12 10:11 UTC, sdkfile approved these changes
제가 수정요청드린 부분은 적용해주셨고, 하비님 대댓글에 달아주신것만 (수정 가능하다면) 해결해주시면 될 것 같습니다! 저는 이쯤에서 어프룹 드리겠습니다 :) @LeoParkProDev

2023-06-14 04:18 UTC, habijung commented on release/scripts/startup/bl_operators/wm.py
> +        # blender 관련
제가 확인이 너무 늦었네요. 이렇게 시간이 지났는줄 몰랐습니다. 반성하겠습니다.
유저가 느끼기에 아시는 분이 아니면 "블렌더가 왜있지?" 하지 않을까? 하는 걱정이었는데, 충분히 스듴님 의견을 이해했기 때문에 그대로 두어도 될 것 같습니다.

2023-06-14 04:19 UTC, LeoParkProDev commented on release/scripts/startup/bl_operators/wm.py
> +            anchor.href = 'https://acon3d.notion.site/Operating-ABLER-9ee94a8169a6400ab9c677dd312e5fdd?pvs=4'
이 부분은 그럼 일어 추가되면 rebase 후 마저 작업해보겠습니다.

2023-06-14 04:23 UTC, habijung commented on release/scripts/startup/bl_operators/wm.py
> +            anchor.href = 'https://acon3d.notion.site/Operating-ABLER-9ee94a8169a6400ab9c677dd312e5fdd?pvs=4'
@LeoParkProDev 
이것도 제가 확인이 너무 늦었습니다.
지금 떠오르는 생각으로는 ACON3D 링크들을 모아두는 dictionary나 모듈이 따로 있고, `anchor`를 인풋으로 받는 함수가 따로 있으면 중복되는 부분이 조금 줄어들 수 있을 것 같습니다.

2023-06-14 05:04 UTC, Youdiie commented on release/scripts/startup/bl_operators/wm.py
> +        for item in json.loads(req.text)["results"]:
요거 아까 구두로 설명 들었는데 버전 패치노트 하나만 넣기위해 release_appeared 작업임을 주석으로 추가 부탁드립니다🙏

2023-06-14 09:06 UTC, JJong84 approved these changes
코드가 깔끔해지고 확장성이 늘어난 것 같아서 정말 좋은 것 같습니다!
몇가지 코멘트 남겼는데, 꼭 고치지는 않아도 될 정도인 것 같아 일단 어프룹 드립니다.

2023-06-14 09:06 UTC, JJong84 commented on release/scripts/startup/bl_operators/wm.py
> +        anchor.href = lang_url_dicts.get(lang, URLs_En).operating_abler
lang_url_dicts.get(lang, URLs_En) 이 부분이 계속 반복되는 것 같은데, 위에서 한번 실행시키고 변수로 저장해서 사용해도 될 것 같습니다!

2023-06-14 09:06 UTC, JJong84 commented on release/scripts/startup/bl_operators/wm.py
> +        anchor.href = lang_url_dicts.get(lang, URLs_En).operating_abler
아니면 함수로 만들어서 사용하는 것도 괜찮아보입니다!
def get_url(lang: string)

2023-06-14 09:06 UTC, JJong84 commented on release/scripts/startup/bl_operators/wm.py
> +    abler_main = "https://acon3d.notion.site/ABLER-User-Guide-316838433d0141ffa4dd11dccc80982c"
URLs_base 가 단순히 default class 의 역할만 하고 있다면, 용도 상으로 아래 `lang_url_dicts.get(lang, URLs_En)` 에서도 이 클래스를 사용하는 것이 의미상 좋을 것 같다고 생각합니다!

2023-06-14 09:08 UTC, LeoParkProDev commented on release/scripts/startup/bl_operators/wm.py
> +        anchor.href = lang_url_dicts.get(lang, URLs_En).operating_abler
오호 더 예뻐질수있겠네요! lang class 까지는 그럼 변수로해서 저장하겠습니다! 감사합니다

2023-06-14 09:09 UTC, LeoParkProDev commented on release/scripts/startup/bl_operators/wm.py
> +    abler_main = "https://acon3d.notion.site/ABLER-User-Guide-316838433d0141ffa4dd11dccc80982c"
이부분은 조금 고민인데요.
추후에 다른 언어가 추가되었을때에,
abler_main 이나, abler_features 같이 일부만 번역이 되는 상황에서, 정의되지 않은 탭은 부모클래스의 영어로 가도록 의도한 것입니다.

2023-06-14 09:12 UTC, LeoParkProDev commented on release/scripts/startup/bl_operators/wm.py
> +        anchor.href = lang_url_dicts.get(lang, URLs_En).operating_abler
이부분 반영했습니다!

2023-06-14 09:16 UTC, JJong84 commented on release/scripts/startup/bl_operators/wm.py
> +    abler_main = "https://acon3d.notion.site/ABLER-User-Guide-316838433d0141ffa4dd11dccc80982c"
base 가 영어인 상황에서 `URLS_En` 을 따로 둔 이유가 있으신가요?

2023-06-14 09:24 UTC, habijung commented on release/scripts/startup/bl_operators/wm.py
> +    abler_main = "https://acon3d.notion.site/ABLER-User-Guide-316838433d0141ffa4dd11dccc80982c"
저는 아예 예전에 만들어둔 `locales.py` 파일이 있는데, 링크 같은 절대값 변수는 아예 따로 빼는 느낌으로 생각했었습니다.

2023-06-15 02:20 UTC, LeoParkProDev commented on release/scripts/startup/bl_operators/wm.py
> +    abler_main = "https://acon3d.notion.site/ABLER-User-Guide-316838433d0141ffa4dd11dccc80982c"
@JJong84  언어를 찾는 부분은 가변 로케일이니 dictionary가 좋아보여서 유지하였고,
스플래쉬에 올라갈 각 페이지는 컴파일타임 고정상수이니 enumclass로 변환하였습니다. 확인부탁드립니다~

2023-06-15 03:58 UTC, LeoParkProDev commented on release/scripts/startup/bl_operators/wm.py
> +            anchor.href = 'https://acon3d.notion.site/Operating-ABLER-9ee94a8169a6400ab9c677dd312e5fdd?pvs=4'
@habijung 위의 내용 반영하였습니다! 함수로는 빼지않고 클래스들을 이용했습니다.

2023-06-15 07:49 UTC, habijung approved these changes

2023-06-15 07:52 UTC, LeoParkProDev commented
@Youdiie 유디님 일어관련된 링크작업하였습니다. 확인부탁드립니다~

2023-06-15 08:09 UTC, Youdiie approved these changes
고생많으셨습니다~~

2023-06-15 08:16 UTC, merged