조명기능 이름변경 및 팝업설명 추가
carpenstreet/blender pull request #362
Opened 2023-06-09 10:43 UTC by LeoParkProDev

## 발제/내용
조명기능 아이템 이름변경 추가
조명기능 팝업 documentation 추가

2023-06-12 08:36 UTC, JJong84 requested changes
@LeoParkProDev
black 포매터 적용이 안 된 것 같은데 적용해주시면 감사하겠습니다!
그리고 [locale 레포지토리 PR](https://github.com/carpenstreet/blender-translations/pull/57#pullrequestreview-1474351661) 합쳐진 후 현 브랜치 서브모듈 업데이트해서 올려주시면 좋을 것 같습니다!

2023-06-12 08:46 UTC, LeoParkProDev commented
> @LeoParkProDev black 포매터 적용이 안 된 것 같은데 적용해주시면 감사하겠습니다! 그리고 [locale 레포지토리 PR](https://github.com/carpenstreet/blender-translations/pull/57#pullrequestreview-1474351661) 합쳐진 후 현 브랜치 서브모듈 업데이트해서 올려주시면 좋을 것 같습니다!

넵 이번 PR에 포맷터 적용 & 서브모듈 업데이트 둘다 반영하겠습니다. 감사합니다.

2023-06-14 02:15 UTC, LeoParkProDev commented
@habijung 하비님 이 건 확인 부탁드립니다~

2023-06-14 02:45 UTC, habijung commented
### 관련 번역 작업

- https://github.com/carpenstreet/blender-translations/pull/57

2023-06-14 02:56 UTC, habijung approved these changes
@LeoParkProDev 
기능 문제는 없는 것으로 확인되었고, 번역 PR 한번만 확인 부탁드립니다!

2023-06-15 04:20 UTC, LeoParkProDev commented
@JJong84 믹스패널이벤트 + submodule update 까지 반영하였습니다 확인부탁드립니다~!

2023-06-15 04:22 UTC, JJong84 approved these changes
@LeoParkProDev 확인했습니다~
그런데 믹스패널 이벤트는 다른 정보 없이 광원 추가/광원 삭제만 들어가기로 한 것일까요?

2023-06-15 04:24 UTC, LeoParkProDev commented
@JJong84 특별한 논의는 없었는데요. 다른 이벤트들보고서 적당한 뎁스를 선택했습니다.
@sdkfile 스듴님 이벤트  세부설정대해서 의견 주실수 있으세요?

2023-06-15 04:27 UTC, sdkfile commented
> @JJong84 특별한 논의는 없었는데요. 다른 이벤트들보고서 적당한 뎁스를 선택했습니다. @sdkfile 스듴님 이벤트 세부설정대해서 의견 주실수 있으세요?

@LeoParkProDev 저는 일단은 저정도로 정의하면 딱 될 것 같습니다!

2023-06-15 04:29 UTC, merged