SWTASK-360 바닐라 블렌더 파일 로드시 경고창 출력
carpenstreet/blender pull request #366
Opened 2023-06-15 07:48 UTC by LeoParkProDev

## 발제/내용
바닐라 블렌더 로드시 경고창 출력

### 어떤 조치를 취했나요?
에이블러에서 블렌더 파일 로드시, 툰쉐이딩 과정중 ACON material이 추가되면서 노드 정보가 바뀜
이를 위해 유저에게 경고 다이얼로그 출력

2023-06-15 07:55 UTC, sdkfile requested changes
마이너한 수정사항입니다! @LeoParkProDev

2023-06-16 00:57 UTC, JJong84 commented on release/scripts/startup/abler/pref.py
> +    bl_idname = "acon3d.ignore_popup"
이 Operator 의 역할이 무엇일까요?

2023-06-16 00:58 UTC, LeoParkProDev commented on release/scripts/startup/abler/pref.py
> +    bl_idname = "acon3d.ignore_popup"
Continue 를 누르면 단순히 팝업이 닫혀야되는데, 기존의 Operator 중에는 그런 역할을 하는게 없어서 인위적으로 구현한 것입니다.
혹시 람다함수라던지 다른 방법이 있다면 알려주시면 감사하겠습니다 ㅠㅠ
@sdkfile @JJong84

2023-06-16 01:04 UTC, JJong84 commented on release/scripts/startup/abler/pref.py
> +    bl_idname = "acon3d.ignore_popup"
@LeoParkProDev warning_modal.py 의 `BlockingModalOperator`, `CloseBlockingModalOperator` 부분 읽어보시면 좋을 것 같습니다!
현재 에이블러에서 특정 모달을 띄우고 닫을 때 저 함수를 사용하고 있습니다!

2023-06-16 11:40 UTC, LeoParkProDev commented on release/scripts/startup/abler/pref.py
> +    bl_idname = "acon3d.ignore_popup"
@JJong84  감사합니다. 딱 필요한 지식이었어요. 잘 사용해서 수정해봤습니다

2023-06-16 11:40 UTC, LeoParkProDev commented on release/scripts/startup/abler/pref.py
> +            text="Node changes may occur when working in abler, and this is at your own risk."
@sdkfile 수정했습니다~

2023-06-19 01:34 UTC, sdkfile approved these changes

2023-06-19 01:35 UTC, JJong84 approved these changes

2023-06-19 01:35 UTC, merged