3D 커서 기반의 조명 생성 기능 추가
carpenstreet/blender pull request #381
Opened 2023-07-26 07:51 UTC by LeoParkProDev

1. 아이콘 토글을 이용해서 3D 커서 좌표에 조명 생성하는 기능 추가
(만약 토글 해제 되어 있다면, 월드좌표계 원점에 생성됨)

2. 조명생성 오퍼레이션 언두 지원
![스크린샷 2023-07-26 오후 4 48 27](https://github.com/carpenstreet/blender/assets/130434011/e103df3a-af64-4ff9-9f11-64678c36ecc1)

![스크린샷 2023-07-21 오후 1 36 42](https://github.com/carpenstreet/blender/assets/130434011/40a40501-9788-41df-b6a8-7f099e55fe40)

2023-07-26 08:02 UTC, Youdiie requested changes
3D 커서 사용법을 SW사업팀에서 유저에게 전달하겠지만 프로그램 내 설명만으로도 충분히 이해가 되면 좋겠습니다.
+요건 기능 영역인데 조명 추가하고나서 생성된 조명이 선택되면 좋을거 같습니다!

2023-07-27 03:57 UTC, LeoParkProDev commented
@Youdiie 이 부분 고민이었던게, 기존에 유저가 레이어등으로 선택을 했을때 캔슬되거나 할까봐 고민이있었는데, 한번 논의해보면 좋아보입니다.

2023-07-27 04:46 UTC, LeoParkProDev commented on release/scripts/startup/abler/custom_properties.py
> +        description="Lights",
작업하였습니다 감사합니다!

2023-07-27 04:47 UTC, LeoParkProDev commented
조명 생성,삭제 UX 개선작업, description 추가해서 올렸습니다!

2023-07-27 05:57 UTC, Youdiie requested changes

2023-07-27 05:57 UTC, Youdiie commented on release/scripts/startup/abler/style_tab/styles_control.py
> +        light.select_set(True)
@LeoParkProDev 선택 바뀌고 조명 리스트에서 light_index도 바껴야할거 같습니다!

2023-07-27 06:06 UTC, LeoParkProDev commented on release/scripts/startup/abler/style_tab/styles_control.py
> +        light.select_set(True)
오 감사합니다. 불쾌한 골짜기 전부 다 찾아주셨네요. 반영했습니다!

2023-07-28 05:05 UTC, JJong84 approved these changes
@LeoParkProDev 잘 동작하는 것 확인해서 어프룹드립니다!
그런데 **"Spawn light on 3D cursor"** => 이 부분 새로 추가되는 부분이라 번역작업도 같이 들어가야할 것 같습니다..!

2023-07-28 05:08 UTC, sdkfile approved these changes
저도 잘 작동하는 것 확인했습니다!

2023-07-28 05:46 UTC, LeoParkProDev commented
감사합니다. 그럼 번역작업 추가후에 확인후 머지하겠습니다~

2023-08-01 02:28 UTC, Youdiie approved these changes
고생하셨습니다~

2023-08-01 05:07 UTC, merged